######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 12 08:48:14 2008
######################################################################

TEMPLATE = app
TARGET = 

UI_DIR = tmp-ui
MOC_DIR = tmp
OBJECTS_DIR = tmp

CONFIG += qt

DEPENDPATH += . ../include/
INCLUDEPATH += . ../include/

# Input
SOURCES += main.cpp

unix:!macx:LIBS += -L../bin/ -lMacNavBar
win32:LIBS += ../MacNavBar.dll
macx:LIBS += -framework MacNavBar

