######################################################################
# Automatically generated by qmake (2.01a) Mo 17. Feb 13:11:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/DMSNavigation.h
SOURCES += src/DMSNavigation.cpp src/main.cpp
