#ifndef OBJECTINSPECTOR_GLOBAL_H
#define OBJECTINSPECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OBJECTINSPECTOR_LIBRARY)
#  define OBJECTINSPECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OBJECTINSPECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OBJECTINSPECTOR_GLOBAL_H
