# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += QIrExpander/qirexpander.h \
    QIrExpander/ui/qirexpander_ui.h \
    QIrExpander/qirexpanderbox.h \
    QIrExpander/qirexpanderstyle.h

#Source files
SOURCES += QIrExpander/qirexpander.cpp \
    QIrExpander/qirexpanderbox.cpp \
    QIrExpander/qirexpanderstyle.cpp
